# -*- coding: utf-8 -*-
"""Programandocomopencv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3Hoos3QK-0GaKnSXkC_G1eK6ms_FAe2
"""

import numpy as np

import cv2 as cv
!wget -q https://github.com/opencv/opencv/raw/master/data/haarcascades/haarcascade_frontalface_default.xml

face_classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')



image = cv.imread('Pessoas.jpg')

image_gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)

# Detectar rostos
faces = face_classifier.detectMultiScale(image_gray, 1.3, 5)

# Desenhar os retângulos
for (x, y, w, h) in faces:
    cv.rectangle(image, (x, y), (x + w, y + h), (255, 0, 0), 2)

# Exibir a imagem com detecção
from google.colab.patches import cv2_imshow

cv2_imshow(image)  # Exibe a imagem no Colab
cv.waitKey(0)
cv.destroyAllWindows()

